### ISSUE TITLE
Event sensor end message for "false" contain only false

### ISSUE THREAD

**Issue by Mannshoch** [naimo84/node-red-contrib-ical-events#36]
**Describe the bug**
If an Event start a message with the Calendar event and msg.payload.on = true get send. But if the Event do end only a msg.payload.on = false get send without any additional information. So I' don't know which event do end.

**To Reproduce**
1. calendar item
2. weblink to *.ics
3. event sensor
4. payload.on =false

**Expected behavior**
the same calendar Item that contain on= false

**node-red-contrib-ical-events
 - Version 0.12.1
 - node-red version 1.0.3
 - nodejs version 12

**Comment by naimo84** [comment]
Hi Mannshoch,

I think it's the correct behaviour of a sensor. Like described here: https://github.com/naimo84/node-red-contrib-ical-events/issues/12#issuecomment-548675425

You can filter via the trigger and match values, in order to get only valuable events.

Or you can use the trigger node, that one is triggering an event start and an event end message.

kind regards,
Benjamin

**Comment by Mannshoch** [comment]
I have no problem with a False event only If nothing there. But if there is knowledge which event is ending It should deliver more Info.
I need the knowledge about what event is ending because I have overlapping events. I need the end of an event to trigger the end of a Job.

Event trigger is not working in any cases I tested. I had never any output from this node.
