### ISSUE TITLE
Add "allDay" to Sensor, and "on" to Upcoming

### ISSUE THREAD

**Issue by dortamur** [naimo84/node-red-contrib-ical-events#81]
**Is your feature request related to a problem? Please describe.**
I need to conditionally check for All Day events from the Sensor node. The Upcoming node data has an "allDay" boolean parameter that does what I want, but this is not present on the Sensor data.

Similarly, I need to filter for current/active events from the Upcoming node. The Sensor node has an "on" attribute which I believe indicates this (although it seems redundant as the Sensor returns current events?) - it would be useful to have a similar indicator on Upcoming node data.

**Describe the solution you'd like**
 * Add "allDay" boolean property to the Sensor payload, to indicate if the Event is All Day or not.
 * Add "on" (or similar) boolean property to the Upcoming payload records, to indicate if the Event is currently on/active.

**Describe alternatives you've considered**
I can add my own Function nodes to calculate and add these values, but given it seems the logic is there for other nodes, it would be cleaner and more consistent to have these states already represented in the payload data.

**Additional context**
n/a

**Comment by naimo84** [comment]
Hi @dortamur ,

since I have already implemented the "allDay" boolean property in all nodes with the version 1.0.0-beta.2, whould you like to test this?

https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.2/node-red-contrib-ical-events-1.0.0-beta.2.tgz

With nodeRED 1.2 and newer you can upload this tgz through the paletee manager ;)

I can add an "on" property, but this would be really redundant and not the purpose of the upcoming node, as I thought initially.

Greets,
Benjamin

**Comment by naimo84** [comment]
Hi,

I've released v1.1.0. May you have a look at it? 
If you like the node, leave it a star ⭐ Thanks.

And I'll close the issue for now, because I think it schould be solved. Feel free to reopen it.

Greetings,
Benjamin
